source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
inhibit_all_warnings!

target 'TreeFood' do
  use_frameworks!

  # Pods for TreeFood
  pod 'SnapKit'
  pod "ESTabBarController-swift"
  pod 'EachNavigationBar'
  pod 'DNSPageView'
  #动画
  pod 'pop', :git => 'https://github.com/facebook/pop.git'
  pod 'FanMenu'
  pod 'LookinServer', :configurations => ['Debug']
  
  #相机
  pod 'DKCamera'
  # 页数
  pod 'CHIPageControl', '~> 0.1.3'
  
  #json
  pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'dev_for_swift5.0'
  pod 'SwiftyJSON'
  
  #日历
  pod 'FSCalendar'
  # 颜色
  #pod 'Colours/Swift'
end
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
